[profile.default]
src = "src"
out = "out"
libs = ["lib"]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"

[etherscan]
arbitrum = { key = "${ARBITRUMSCAN_API_KEY}" }
